tweetanalysis:
  links:
    - db
  image: jbuitrago/tweetanalysis:def
  environment:
    time : "15"
    access_token_key : "************************************************"
    access_token_secret : "************************************************"
    consumer_key : "************************************************"
    consumer_secret : "************************************************"

web:
  links:
    - db
  image: jbuitrago/web:def
  ports:
    - "5000:5000"
    
db:
  image: mongo:3.0.2
